# Generated by Django 2.0.5 on 2018-07-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_status', models.CharField(blank=True, max_length=30)),
                ('extracted_info', models.CharField(blank=True, max_length=255)),
                ('place', models.CharField(blank=True, max_length=30)),
                ('seen', models.IntegerField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
